
[functions.blockscout]
enabled = true
verify_jwt = true
import_map = "./functions/blockscout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/blockscout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/blockscout/*.html" ]

[functions.cron-test]
enabled = true
verify_jwt = true
import_map = "./functions/cron-test/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cron-test/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cron-test/*.html" ]

[functions.admin-purchases]
enabled = true
verify_jwt = true
import_map = "./functions/admin-purchases/deno.json"
entrypoint = "./functions/admin-purchases/index.ts"

[functions.team-verify]
enabled = true
verify_jwt = true
import_map = "./functions/team-verify/deno.json"
entrypoint = "./functions/team-verify/index.ts"
